<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>deleted</key>
	<array>
		<string>keyEquivalent</string>
	</array>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>1AD8EB10-62BE-417C-BC4B-29B5C6F0B36A</string>
</dict>
</plist>
