<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>deleted</key>
	<array>
		<string>keyEquivalent</string>
	</array>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>15615A0C-37B0-4B3F-9105-53ED536AFBB4</string>
</dict>
</plist>
