<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>changed</key>
	<dict>
		<key>repository.block.patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#yaml_front_matter</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#separator</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#heading</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#blockquote</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#lists</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#raw_block</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#link-def</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#html</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#paragraph</string>
			</dict>
		</array>
		<key>repository.block.repository.raw_block.patterns</key>
		<array>
			<dict>
				<key>begin</key>
				<string>(^|\G)([ ]{4}|\t)</string>
				<key>name</key>
				<string>markup.raw.markdown</string>
				<key>while</key>
				<string>(^|\G)([ ]{4}|\t)</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>(^|\G)```</string>
				<key>end</key>
				<string>(^|\G)([ \t]+)?```</string>
				<key>name</key>
				<string>markup.raw.markdown</string>
			</dict>
		</array>
		<key>repository.block.repository.yaml_front_matter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G---</string>
					<key>end</key>
					<string>^---</string>
					<key>name</key>
					<string>source.yaml.embedded.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.yaml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>deleted</key>
	<array>
		<string>repository.block.repository.raw_block.begin</string>
		<string>repository.block.repository.raw_block.name</string>
		<string>repository.block.repository.raw_block.while</string>
	</array>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>0A1D9874-B448-11D9-BD50-000D93B6E43C</string>
</dict>
</plist>
